### ISSUE TITLE
How to download the assetbundles from a specific http url? 

### ISSUE THREAD

**Issue by richfuns** [SadPandaStudios/AssetBundleManager#12]
For example=>I need to download the bundle from http://127.0.0.1/subgame.ab

Is that possible to use this library? 

Thanks in advance.

**Comment by richfuns** [comment]
When I set the base url =http://127.0.0.1/

I got the below errors:

`Error downloading [http://127.0.0.1/StandaloneWindows/StandaloneWindows]: [404] [Generic/unknown HTTP error]
UnityEngine.Debug:LogError(Object)
AssetBundles.<Download>c__Iterator0:MoveNext() (at Assets/Script/libs/ab/AssetBundleDownloader.cs:121)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)`

I do not know what is wrong with it. 

Please help me. 

Thanks.

**Comment by FodderMK** [comment]
ABM is looking for a bundle called `StandaloneWindows` in the folder `StandaloneWindows` on your web server  This bundle is the manifest and is created by Unity's AssetBundleBrowser when you make bundles for standalone builds.

Are you able to download the bundle from that url using a browser?

**Comment by richfuns** [comment]
@FodderMK  Thank you for your replying friend.

I can definitely download the manifest bundle which created by AssetBundleBrowser from this url: http://127.0.0.1/StandaloneWindows

Here is the local web server directory details: 

![baidushurufa_2018-9-17_12-29-35](https://user-ima
ges.githubusercontent.com/1400999/45606175-6e57fc00-ba75-11e8-8e0a-c858a74ccdeb.png)

But When I call it from unity, got errors below:

![baidushurufa_2018-9-17_12-24-40](https://user-images.githubusercontent.com/1400999/45606079-b7f41700-ba74-11e8-8398-8cb831b3aa63.png)


Here is my test code:

`using System.Collections;
using System.Collections.Generic;
using AssetBundles;
using UnityEngine;
using Logger = Script.Logger;

/// <summary>
/// The way to use AMB
/// https://github.com/SadPandaStudios/AssetBundleManager
/// </summary>
public class ABMExample1 : MonoBehaviour
{
    private AssetBundleManager abm;

    // Use this for initialization
    IEnumerator  Start()
    {
        
        Debug.Log("ABM Start()");
        
        abm = new AssetBundleManager();
        abm.SetBaseUri("http://127.0.0.1/");

        var initializeAsync = abm.InitializeAsync();
        yield return initializeAsync;

        if (initializeAsync.Success)
        {
            AssetBundleAsync bundle = abm.GetBundleAsync("subgame");
            yield return bundle;
            
            AssetBundle ab = bundle.AssetBundle;

            if (ab!=null)
            {
                Object[] obj = ab.LoadAllAssets<Object>();
                Debug.Log("Source count：" + obj.Length);

                foreach (Object o in obj)
                {
                    Debug.Log("asset:" + o.name);
                }

                abm.UnloadBundle(ab);
            }
        }
        else
        {
            Debug.LogError("Error initializing ABM.");
        }
        
        abm.Dispose();
    }

    // Update is called once per frame
    void Update()
    {
    }
}`

It seems that the url=http://127.0.0.1/StandaloneWindows/StandaloneWindows  is wrong. 
The directory StandaloneWindows is redundant. May be your library added the directory StandaloneWindows automatically that resulted in those errors.

**Comment by FodderMK** [comment]
The directory structure is by design.  When Unity makes asset bundles it creates a manifest file containing information about those bundles.  The name of the manifest file is the same as the folder that Unity builds into.  By default the Unity AssetBundle Browser uses the platform type as the folder name.  This allows you to easily have multiple platforms on a single webserver.  For example, if you have two bundles called MyBundle1 and MyBundle2 and you build those bundles for multiple platforms you will end up with a directory structure like the following:

```http://127.0.0.1
| /StandaloneWindows    <-- This folder contains all StandaloneWindows bundles
  | /StandaloneWindows  <-- This is the manifest for bundles in this folder
  | /MyBundle1
  | /MyBundle2
| /Android    <-- This folder contains all Android bundles
  | /Android  <-- This is the manifest for bundles in this folder
  | /MyBundle1
  | /MyBundle2
```

ABM expects the manifest file for your Android bundles to be located at `http://127.0.0.1/Android/Android` and MyBundle1 at `http://127.0.0.1/Android/MyBundle1`.  

Keep in mind that ABM was built to work alongside Unity's AssetBundle Browser.  I notice your bundles have the extension `.ab`, which does not appear to be a standard extension for bundles (at least on the tests I've done).  You may need to modify ABM to work with your folder and file structure.
