### ISSUE TITLE
[Request] Download queue and clear specific bundle

### ISSUE THREAD

**Issue by brickhawkins** [SadPandaStudios/AssetBundleManager#13]
I tried to expose the download queue size to make download progress looks like:

current / total files to download
download progress %

but, i can't figure it out how to expose on the ABM class.
also, do manifest contain information for total file size (with dependency)?

Finally deleting specific assetbundle, it can be done with
Caching.ClearCachedVersion(assetbundleName, Hash128)
how to get the downloaded bundle's hash128?
or, is there another way to delete specific downloaded bundle?
Could you give me the explanation?
Thanks

**Comment by FodderMK** [comment]
I don't have anything in the main branch for seeing download progress but I may have what you're looking for in the `feature/download-progress-hook` branch .  I haven't merged that back into `master` yet because I haven't given it much testing.  If you do use it and don't encounter any problems let me know and I can look at getting it into `master`.

As far as I know the manifest doesn't contain file size information so this is something you would need to handle on your own.

You can get the hash from the manifest file after it has been downloaded:

```
var abm = new AssetBundleManager();

// Do standard initialization
[...]

var manifest = abm.Manifest;
var hash = manifest.GetAssetBundleHash("MyBundleName");
```
