### ISSUE TITLE
How long are you planning to support AssetBundleManager?

### ISSUE THREAD

**Issue by dhawalbanker** [SadPandaStudios/AssetBundleManager#27]
I believe the last release was in Oct 2020, hence I am assuming it is supported for Unity 2020. But what's the future support plan going ahead?

**Comment by FodderMK** [comment]
If you find that this package is broken in a version of Unity then let us know and we'll take a look.  My understanding is that Unity is recommending Addressables on the newest releases so that's something I would explore.  At the moment none of the games I develop are on the latest Unity version so I haven't had an opportunity to try Addressables out.  If it turns out I hate them then this opinion may change.
