### ISSUE TITLE
Cannot connect to destination host error

### ISSUE THREAD

**Issue by WOLKYDJ** [SadPandaStudios/AssetBundleManager#6]
I'm trying load my datas but giving error. Error downloading [/Users/****/Desktop/Unity Projects/***/AssetBundles/Android/Android]: [Cannot connect to destination host] there are two android folder but I have one android folder. I did not understand what's going on

**Comment by FodderMK** [comment]
The second `/android` is a part of the asset bundle manifest.  Inside the `/Users/*/Desktop/Unity Projects/AssetBundles/Android/` folder you should have an `Android` file and an `Android.manifest` file.  These files are created by Unity when building asset bundles and always match the name of the folder you build the bundles into.  ABM needs the information in those files to determine bundle dependencies and caching.

It looks like you are attempting to use local files instead of files on a web server.  If you're just testing stuff in the editor then you can put `file://` as the start of the uri.

`abm.SetBaseUri("file:///Users/*/Desktop/Unity Projects/AssetBundles");`

If you are using Unity's Asset Bundle Browser to build these bundles in the "default" location then you could also try the simulated uri

`abm.UseSimulatedUri();`

**Comment by WOLKYDJ** [comment]
Thanks it solved. but I have one more question. when i play the game it is downloading but where location? Also How can my objects read the sources? because I have 3 folder Sprites, Animation and Sounds. I built the folders in Asset Bundle Browser already. But how can it read?

**Comment by FodderMK** [comment]
Unity has a caching system that it uses to store downloaded bundles.  You can see where it is by running the following:

`Debug.Log(Caching.defaultCache.path);`

As for how to use the bundles, I recommend checking out the Unity documentation about the AssetBundle class and maybe a few tutorials on how to use them. 

https://docs.unity3d.com/ScriptReference/AssetBundle.html

**Comment by WOLKYDJ** [comment]
Well, is this at once? I don't want the download when every open the app.

**Comment by FodderMK** [comment]
The manifest file is downloaded every time, all other files use the caching system.  If ABM cannot download the manifest file it attempts to use the one previously downloaded.  As long as  are able to connect to the internet once to get the manifest file and all its bundles then they should be able to play offline.

You shouldn't need to use `DownloadHandlerAssetBundle`, what happens if you use `GetBundle` in ABM?

**Comment by WOLKYDJ** [comment]
I get it. I'll use the Example script at a button but if manifest downloaded, then a massage should show to user as "this application has content already". my manifest is downloading your script but how can i read it at runtime? before build the application, will i delete these folders? because if I delete these then my app's size will increase

**Comment by FodderMK** [comment]
I'm having a difficult time understanding the question so my apologies.

The manifest file is very small and shouldn't be too much for your clients to download each time.  If ABM can't download a manifest file then it will attempt to use one previously downloaded.  If you are using Unity 2017 or greater than old manifest files are deleted after a successful download so you shouldn't need to worry about disk space for the manifest file.

For the other bundles downloaded, ABM will use the cached version if they are available, otherwise it will download the bundle and cache it to be used later.  If your players have downloaded the bundles then they should be able to play the game offline.

You do not need to include any asset bundles anywhere in your application during build time.  As long as they are available on a public web server somewhere then ABM will be able to download them.

If your asking about a way to know if a bundle needs to be downloaded or not, then no.  Currently ABM does not have a way to tell you if a bundle is cached or needs to be downloaded.  That could probably be added if you wanted to make a feature request.

If you're asking how to get the manifest from ABM, previously that was not possible but I have now made it a public property.

**Comment by FodderMK** [comment]
It sounds like the original issue has been resolved so I am going to close this ticket.  Feel free to open another if you discover an error!
